defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      permalink: /:path/:basename/
  - scope:
      path: "assets"
    values:
      permalink: /:path/:basename:output_ext

collections:
  posts:
    permalink: /articles/:year/:month/:day/:title:output_ext

show_drafts: true
